plaid:
  hostName: 5ec3fd44ba7c950013a7e342
  clientId: 5ec3fd44ba7c950013a7e342
  publicKey: d675c8e77a29deb226beba95a7c92d
  secret: 977289bc139aed2db157e548be3e61
  products: transactions
  countryCodes: US
  oAuthRedirectUri: ""
  oAuthNone: ""
server:
  port: 9226

## Datasource configuration
buckzy:
  account:
    datasource:
      driverClass: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/buckzy
      datasource:
        username: buckzyadmin
        password: buckzyadmin
    kafka:
      url: localhost:9092
spring:
  application:
    name: Beamservice
  datasource:
    url: jdbc:postgresql://localhost:5432/buckzy?currentSchema=buckzy
    username: buckzyadmin
    password: buckzyadmin
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true